### ISSUE TITLE
R2R Test Unseen

### ISSUE THREAD

**Issue by jasscia18** [GengzeZhou/Recurrent-VLN#1]
Thank you so much for the great work you do. I reproduced Recurrent VLN on the R2R datasets according to the file readme.md.  
But we only get the results for the validation set,  how can I get the results of the Test Unseen?

**Comment by GengzeZhou** [comment]
Thanks for pointing out.
The validation code has been revised. Now you can obtain the submitted JSON file by running:
```bash
bash run/test_agent.bash
```
The results will be saved to `logs/VLNBERT-test-Prevalent/snap/submit_test_unseen.json`.
